backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use backend\models\OperationAvailabilityForm;
use common\models\active_record\ArithmeticOperations;
use common\models\LoginForm;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;

/**
 * Site controller
 */
class SiteController extends Controller
{

    public function beforeAction($action)
    {
        if(parent::beforeAction($action)) {
            $user = Yii::$app->user->identity;
            if($user and $user->email != 'viperoussnake@yandex.ru') {
                Yii::$app->user->logout();
                $this->goHome();
                //return $this->redirect(Yii::$app->params['frontendHost']);
            }
        }

        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'change-operation'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }


    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $calculatorDataProvider = new ActiveDataProvider([
            'query' => (new ArithmeticOperations())->find()
        ]);

        return $this->render('index' , [
            'calculatorDataProvider' => $calculatorDataProvider,
        ]);
    }

    /**
     * @return array
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionChangeOperation() {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $form = new OperationAvailabilityForm();

        if($form->load(Yii::$app->request->post(), '') && $form->validate() && $form->save()) {
            return [
                'success' => true,
            ];
        }
        else{
            return [
                'success' => false,
                'errors' => $form->errors
            ];
        }
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use frontend\components\BcBigNumberCalculator;
use frontend\models\CalculatorModel;
use Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index'],
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }


    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $operationResult = '';
        $model = new CalculatorModel([
            'calculator' => new BcBigNumberCalculator()
        ]);
        if($model->load(Yii::$app->request->get()) && $model->validate()) {
            $operationResult = $model->perform();
        }

        return $this->render('index' , [
            'model' => $model,
            'operationResult' => $operationResult,
        ]);
    }
}

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/index.php
<?php

/* @var $this yii\web\View */

/* @var $calculatorDataProvider \yii\data\BaseDataProvider */

$this->title = 'Калькулятор';
?>
<div class="site-index">

    <div class="body-content">

        <div class="row">
            <div class="col-lg-12">
                <h2>Калькулятор</h2>
                <?php
                    echo \yii\grid\GridView::widget([
                        'dataProvider' => $calculatorDataProvider,
                        'columns' => [
                            'id',
                            'code',
                            [
                                'class' => 'yii\grid\DataColumn',
                                'header' => 'available',
                                'content' => function($model, $key, $index, $column) {
                                    return '<input data-url="' . \yii\helpers\Url::to('site/change-operation') . '" data-id="'
                                        . $model->id . '" class="js-change-operation-avalabilty" type="checkbox" '
                                        . ($model->available ? 'checked' : '') . ' />';
                                }
                            ],
                        ]
                    ]);
                ?>
            </div>

        </div>

    </div>
</div>